CREATE TABLE `Users` (
   `id` INT AUTO_INCREMENT,
   `name` VARCHAR(50) NOT NULL,
   `surname` VARCHAR(50) NOT NULL,
   `age` INT,
   `nickname` VARCHAR(50) NOT NULL,
   `email` VARCHAR(100) NOT NULL UNIQUE,
   `sex` BIT NOT NULL,
   `description` VARCHAR(255),
   `Role` VARCHAR(20) NOT NULL CHECK (Role IN ('Owner', 'Professional')),
   `IsVerified` BOOLEAN DEFAULT FALSE,
   `createdAt` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
   `updatedAt` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
    PRIMARY KEY (`id`)
);
